---
---
- name: Create monitoring directory
  file:
    path: "{{ monitoring_install_path }}"
    state: directory
    mode: '0755'

- name: Render docker-compose.yml from template
  template:
    src: docker-compose.yml.j2
    dest: "{{ monitoring_install_path }}/docker-compose.yml"
    mode: '0644'
  notify: restart monitoring stack


- name: Launch monitoring stack
  command: docker compose up -d
  args:
    chdir: "{{ monitoring_install_path }}"
