services:
  nginx-proxy:
    image: nginx:stable
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - zabbix-web
      - grafana
    networks:
      - zabbix-net
    restart: unless-stopped

networks:
  zabbix-net:
    external: true
