services:

  postgres-server:
    image: postgres:15-alpine
    container_name: zbx-postgres
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      POSTGRES_DB: zabbix
    volumes:
      - ./zbx_env/pg_data:/var/lib/postgresql/data
    networks:
      - zbx_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zbx-server
    depends_on:
      - postgres-server
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ${ZBX_DB_PASSWORD}
      ZBX_SERVER_NAME: ${ZBX_SERVER_NAME}
      ZBX_TIMEZONE: ${ZBX_TIMEZONE}
    volumes:
      - ./zbx_env/alertscripts:/usr/lib/zabbix/alertscripts
      - ./zbx_env/externalscripts:/usr/lib/zabbix/externalscripts
    ports:
      - "10051:10051"
    networks:
      - zbx_net
    healthcheck:
      test: ["CMD", "sh", "-c", "zabbix_server -V >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zbx-web
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Tehran
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - zbx_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/index.php"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    container_name: zbx-agent
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: docker-host
    networks:
      - zbx_net
    ports:
      - "10050:10050"
    healthcheck:
      test: ["CMD", "zabbix_agentd", "-V"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  zbx_net:
    driver: bridge
