services:
  postgres:
    image: postgres:15
    container_name: zabbix_postgres
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ${ZBX_DB_PASSWORD}
      POSTGRES_DB: zabbix
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:${ZABBIX_VERSION}
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ${ZBX_DB_PASSWORD}
      ZBX_SERVER_NAME: ${ZBX_SERVER_NAME}
    depends_on:
      - postgres
    ports:
      - "10051:10051"
      - "10050:10050"
    restart: unless-stopped
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD-SHELL", "zabbix_server -V >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:${ZABBIX_VERSION}
    container_name: zabbix-frontend
    environment:
      DB_SERVER_HOST: postgres
      ZBX_SERVER_HOST: zabbix-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ${ZBX_DB_PASSWORD}
      PHP_TZ: ${ZBX_TIMEZONE}
    depends_on:
      - postgres
      - zabbix-server
    ports:
      - "${ZABBIX_FRONTEND_PORT}:8080"
    restart: unless-stopped
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: docker-agent
    group_add:
      - 111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zabbix-server
    restart: unless-stopped
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "zabbix_agent2", "-t", "agent.ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  pgdata:

networks:
  zabbix-net:
    external: true
