---
# defaults file for roles/monitoring
monitoring_install_path: /opt/monitoring
img_db: postgres:15
img_zbxsrv: zabbix/zabbix-server-pgsql:alpine-7.0-latest
img_zbxweb: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
img_zbxagt: zabbix/zabbix-agent2:alpine-7.0-latest
img_grf: grafana/grafana:latest

db_container: zabbix_postgres
db_host: postgres
db_user: zabbix
db_pass: zabbixpass
db_name: zabbix

zbxsrv_container: zabbix-server
zbxsrv_name: Zabbix Docker Monitoring
zbxsrv_port1: 10051
zbxsrv_port2: 10050

zbxweb_container: zabbix-frontend
zbxweb_tz: Asia/Tehran
zbxweb_port: 8080

grf_container: grafana
grf_port: 3000

network: zabbix-net

