---
- name: Install Docker Compose plugin
  hosts: monitoring
  become: yes

  tasks:
    - name: Create plugin directory
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'

    - name: Download Docker Compose binary
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'

    - name: Ensure docker-compose is working
      command: docker compose version
      register: compose_output
      changed_when: false

    - name: Show docker-compose version
      debug:
        var: compose_output.stdout
