---
- name: Connectivity test to Monitoring Server
  hosts: monitoring
  become: true
  tasks:
    - name: Connectivity test with ping module
      ansible.builtin.ping:

    - name: to show uptime of system
      ansible.builtin.shell: uptime
      register: uptime_result

    - name: result of uptime command
      ansible.builtin.debug:
        var: uptime_result.stdout

